# Site settings
title: Terminal Cheat Sheet
email: hello@terminalcheatsheet.com
description: > # Ignore newlines until "baseurl:"
  All the knowledge you need to get up and
  running on terminals across operating systems.
baseurl: "" # Subpath of the site. Currently no subpath
url: "https://terminalcheatsheet.com" # Base protocol and hostname
github_username: devadvance

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "demo_env/**"
    values:
      sitemap: false
  -
    scope:
      path: "i18n/new_language_templates/**"
    values:
      sitemap: false
  -
    scope:
      path: "i18n/fr/**"
    values:
      sitemap: false